sudo: requiredcsharp
dist: bionic
language: csharp
mono: none
dotnet: 8.0
services: docker
before_install:
  - cd Person/
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag rest-with-asp-net-udemy:latest "$DOCKER_USERNAME"/rest-with-asp-net-udemy;
    docker tag rest-with-asp-net-db:latest "$DOCKER_USERNAME"/rest-with-asp-net-db;
    docker push "$DOCKER_USERNAME"/rest-with-asp-net-udemy;
    docker push "$DOCKER_USERNAME"/rest-with-asp-net-db;
  on:
    brach: master
notifications:
  email: rogerio_test@hotmail.com