CREATE TABLE IF NOT EXISTS person (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(80) NOT NULL,
    last_name VARCHAR(80) NOT NULL,
    address VARCHAR(100) NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    gender VARCHAR(6) NOT NULL,
    PRIMARY KEY (id)
);
